# Generated by Django 6.0 on 2025-12-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='guardian_date_of_birth',
            field=models.DateField(blank=True, help_text="Guardian's date of birth (for minors)", null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_occupation',
            field=models.CharField(blank=True, help_text="Guardian's occupation (for minors)", max_length=100, null=True),
        ),
    ]
