# Generated by Django 6.0 on 2025-12-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='other_relation',
            field=models.CharField(blank=True, help_text="Specify relationship if 'Other' is selected", max_length=100, null=True),
        ),
    ]
