# Generated by Django 6.0 on 2025-12-07 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About DentHub', max_length=200)),
                ('description', models.TextField(default='DentHub Dental Clinic has been serving the community with exceptional dental care for over a decade.')),
                ('patients_count', models.CharField(default='10,000+', max_length=20)),
                ('patients_label', models.CharField(default='Happy Patients', max_length=50)),
                ('years_count', models.CharField(default='15+', max_length=20)),
                ('years_label', models.CharField(default='Years Experience', max_length=50)),
                ('dentists_count', models.CharField(default='25+', max_length=20)),
                ('dentists_label', models.CharField(default='Expert Dentists', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Contact Us', max_length=200)),
                ('section_subtitle', models.TextField(default='Get in touch with us for appointments or inquiries')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('footer_text', models.TextField(default='© 2024 DentHub Dental Clinic. All rights reserved.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to DentHub Dental Clinic', max_length=200)),
                ('subtitle', models.TextField(default='Your smile is our priority. Experience world-class dental care with cutting-edge technology and compassionate professionals.')),
                ('primary_button_text', models.CharField(default='Book Appointment', max_length=50)),
                ('primary_button_link', models.CharField(default='#contact', max_length=200)),
                ('secondary_button_text', models.CharField(default='Our Services', max_length=50)),
                ('secondary_button_link', models.CharField(default='#services', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('fa-teeth', 'Teeth'), ('fa-smile-beam', 'Smile Beam'), ('fa-tooth', 'Tooth'), ('fa-user-md', 'Doctor'), ('fa-crown', 'Crown'), ('fa-child', 'Child'), ('fa-x-ray', 'X-Ray'), ('fa-syringe', 'Syringe')], default='fa-tooth', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='DentHub', max_length=100)),
                ('patient_portal_url', models.URLField(default='http://192.168.1.18:5174')),
                ('primary_color', models.CharField(default='#00B2A9', help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(default='#0097A7', help_text='Hex color code', max_length=7)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('about_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='website_content.aboutsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
