# Generated by Django 6.0 on 2025-12-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ['order'], 'verbose_name': 'Hero Slide', 'verbose_name_plural': 'Hero Slides'},
        ),
        migrations.AddField(
            model_name='herosection',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order in carousel (lower numbers appear first)'),
        ),
    ]
