# Generated by Django 6.0 on 2025-12-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_content', '0002_alter_herosection_options_herosection_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Upload HD background image for this slide', null=True, upload_to='hero_images/'),
        ),
    ]
