# Generated by Django 6.0 on 2025-12-07 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_content', '0003_herosection_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='icon',
            field=models.CharField(choices=[('fa-tooth', 'Tooth'), ('fa-teeth', 'Teeth'), ('fa-smile-beam', 'Smile Beam'), ('fa-user-md', 'Doctor'), ('fa-star', 'Star'), ('fa-heart', 'Heart'), ('fa-shield-alt', 'Shield'), ('fa-award', 'Award'), ('fa-magic', 'Magic'), ('fa-crown', 'Crown')], default='fa-tooth', help_text='Icon to display when no background image is set', max_length=50),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order in carousel (0-4, maximum 5 slides)', validators=[django.core.validators.MaxValueValidator(4)]),
        ),
    ]
