# Generated by Django 6.0 on 2025-12-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_content', '0004_herosection_icon_alter_herosection_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='carousel_interval',
            field=models.IntegerField(default=5000, help_text='Carousel auto-slide interval in milliseconds (e.g., 5000 = 5 seconds)'),
        ),
    ]
