# Generated by Django 6.0 on 2025-12-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_content', '0005_sitesettings_carousel_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='patient_portal_url',
            field=models.URLField(default='http://192.168.1.18:5173'),
        ),
    ]
