# Generated by Django 6.0 on 2025-12-13 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_content', '0006_alter_sitesettings_patient_portal_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_recurring', models.BooleanField(default=True, help_text='If true, use month/day as an annual recurrence')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12)])),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31)])),
                ('specific_date', models.DateField(blank=True, help_text='Optional specific date for one-off holidays', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['is_recurring', 'month', 'day', 'specific_date', 'name'],
            },
        ),
    ]
