# Generated by Django 6.0 on 2025-12-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_message_deleted_by_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
