# Generated by Django 6.0 on 2025-12-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_user_force_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='friday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='friday_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='friday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='monday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='monday_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='monday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='saturday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='saturday_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='saturday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='sunday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='sunday_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='sunday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='thursday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='thursday_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='thursday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='tuesday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='tuesday_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='tuesday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='wednesday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='wednesday_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='wednesday_open',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
