# Generated by Django 6.0 on 2025-12-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_branch_friday_close_branch_friday_closed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='employees', to='employees.department'),
        ),
    ]
